### ISSUE TITLE
XTBox.exe not opening

### ISSUE THREAD

**Issue by MD55DM** [xemulat/XToolbox#22]
Describe the bug: After launching the .exe (even in Admin mode) and accepting the License , I get the following:

**[S>] Initializing Libraries...
[S>] Checking hardware requirements...
[S>] Running Pre-Startup tasks...
[S>] Checking updates...
Traceback (most recent call last):
  File "XTBox.py", line 665, in <module>
  File "ping3\__init__.py", line 83, in wrapper
  File "ping3\__init__.py", line 310, in ping
  File "ping3\__init__.py", line 83, in wrapper
  File "ping3\__init__.py", line 176, in send_one_ping
OSError: [WinError 10022] An invalid argument was supplied
[4144] Failed to execute script 'XTBox' due to unhandled exception!**

Also tested with Antivirus fully disabled, no change.

My computer:
OS: Win 11 fully updated
Browser Chrome (latest)
XToolbox version: 2.5
Python installed version: 3.10.10

Thanking in advance for any help

**Comment by xemulat** [comment]
Try rebooting your router, moving the file to the desktop. No need to run as admin.

**Comment by xemulat** [comment]
Please respond if it helped.

**Comment by Ecorous** [comment]
Can this issue be closed?

**Comment by MD55DM** [comment]
Yes, thanks again for assistance.
